//MIDI CC MAP CHART FOR CC DEFAULTS
#define CC_MAX_VAL 127

#define CC_OSC1_MIX_LEVEL 30
#define CC_OSC1_WAVE_FORM 34
#define CC_OSC2_MIX_LEVEL 31
#define CC_OSC2_WAVE_FORM 35

//Amp Envelope
#define CC_AMP_ENV_ATTACK 38
#define CC_AMP_ENV_DECAY 39
#define CC_AMP_ENV_SUSTAIN 40
#define CC_AMP_ENV_RELEASE 41

//Filter Envelope
#define CC_FILTER_ENV_ATTACK 42
#define CC_FILTER_ENV_DECAY 43
#define CC_FILTER_ENV_SUSTAIN 44
#define CC_FILTER_ENV_RELEASE 45
